// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgOvsBHhjILXu5SzIaYmLfJy6iPh6wFxE',
    appId: '1:2304558075:web:54f29def5a3ac2ba78c15e',
    messagingSenderId: '2304558075',
    projectId: 'appdemo-3d1ab',
    authDomain: 'appdemo-3d1ab.firebaseapp.com',
    storageBucket: 'appdemo-3d1ab.firebasestorage.app',
    measurementId: 'G-ZX3BCV43KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6CRDpiw61V3LfW1nGT4vEoiV_crgrbCY',
    appId: '1:2304558075:android:cd861b1140a92b4b78c15e',
    messagingSenderId: '2304558075',
    projectId: 'appdemo-3d1ab',
    storageBucket: 'appdemo-3d1ab.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuHtILN6tE5KhwzvG1gzQSRwooq8EWzAs',
    appId: '1:2304558075:ios:45ceba1ce2b5984478c15e',
    messagingSenderId: '2304558075',
    projectId: 'appdemo-3d1ab',
    storageBucket: 'appdemo-3d1ab.firebasestorage.app',
    iosBundleId: 'com.imagetoprompt.ai',
  );
}
